version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80" # Render se encargará de redirigir al puerto HTTP
    depends_on:
      - db # Asegura que MySQL esté listo antes de iniciar la app
    environment:
      APP_ENV: production
      APP_DEBUG: false
      APP_KEY: ${APP_KEY} # Render sincroniza esta variable
      APP_URL: https://your-app.onrender.com
      DB_CONNECTION: mysql
      DB_HOST: db # Nombre del servicio MySQL en este archivo
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: root
      DB_PASSWORD: root

  db:
    image: mysql:8.0
    container_name: laravel-database
    ports:
      - "3306:3306" # Este puerto es interno para la comunicación de Docker
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - dbdata:/var/lib/mysql # Persistencia de datos

volumes:
  dbdata:
